#!/usr/bin/env python3
"""
Head Thermoelastic Model — RF IQ → perceived audio WAV

Models the two-stage Frey effect process:
1. RF burst → thermoelastic pressure transient in brain tissue
2. Skull resonance bandpass → cochlear perception

The brain acts as a natural low-pass filter:
- Individual pulses (200 kHz PRF) merge thermally into burst envelopes
- Skull resonant modes (~7-15 kHz) set the perceived carrier pitch
- BRF modulation envelope carries the audio content (AM radio principle)

Adjustable parameters:
- Skull resonance frequency (7-15 kHz, depends on head size)
- Acoustic attenuation (0.5-1.0 dB/cm/MHz through ~7 cm brain tissue)
- Thermal time constant (ms, how fast tissue cools between pulses)

Usage:
  python head_model_wav.py captures/sentinel_634MHz_*.iq --output speech_test.wav
  python head_model_wav.py --top 10                # top 10 Zone A by kurtosis
  python head_model_wav.py --all-zone-a            # all Zone A captures
"""

import os
import sys
import json
import glob
import argparse
import numpy as np
from pathlib import Path

SAMPLE_RATE_SDR = 2_400_000
SETTLE_SAMPLES = 48_000
DC_NOTCH_BINS = 32
OUTPUT_DIR = "results/audio"
Path(OUTPUT_DIR).mkdir(exist_ok=True)


def load_iq(filepath):
    """Load RTL-SDR IQ, strip settle, DC notch."""
    raw = np.fromfile(filepath, dtype=np.uint8)
    if len(raw) < (SETTLE_SAMPLES + 1000) * 2:
        return None
    iq = (raw.astype(np.float32) - 127.5) / 127.5
    z = iq[0::2] + 1j * iq[1::2]
    z = z[SETTLE_SAMPLES:]
    Z = np.fft.fft(z)
    h = DC_NOTCH_BINS // 2
    Z[:h] = 0
    Z[-h:] = 0
    z = np.fft.ifft(Z)
    return z


def thermoelastic_model(z, skull_freq_hz=10000, attenuation_db_per_cm_mhz=0.7,
                        brain_path_cm=7.0, thermal_tau_us=50.0,
                        audio_sample_rate=44100):
    """
    Model the thermoelastic Frey effect process:

    1. Compute instantaneous RF power (|IQ|²)
    2. Apply thermal low-pass filter (tissue can't cool between rapid pulses)
    3. Compute thermoelastic pressure (proportional to dT/dt)
    4. Apply skull resonance bandpass filter
    5. Downsample to audio rate
    6. Apply acoustic attenuation

    Returns: audio waveform at audio_sample_rate
    """
    # Step 1: Instantaneous power deposition (proportional to |E|²)
    power = np.abs(z) ** 2

    # Step 2: Thermal accumulation — exponential moving average
    # Pulses within a burst superpose thermally because they arrive
    # faster than tissue can cool (thermal tau ~ 50-500 μs)
    tau_samples = int(thermal_tau_us * 1e-6 * SAMPLE_RATE_SDR)
    if tau_samples < 1:
        tau_samples = 1
    alpha = 1.0 / tau_samples
    thermal = np.zeros_like(power)
    thermal[0] = power[0]
    for i in range(1, len(power)):
        thermal[i] = alpha * power[i] + (1 - alpha) * thermal[i - 1]

    # Step 3: Thermoelastic pressure = rate of temperature change (dT/dt)
    # The acoustic transient is generated by the time derivative of temperature
    pressure = np.diff(thermal)
    pressure = np.append(pressure, 0)

    # Step 4: Skull resonance bandpass filter
    # The skull acts as a resonant cavity with Q ~ 5-15
    # Bandpass around skull_freq_hz with bandwidth skull_freq/Q
    from scipy.signal import butter, sosfilt

    Q = 10  # skull resonance quality factor
    bw = skull_freq_hz / Q
    low = max(skull_freq_hz - bw / 2, 100)
    high = min(skull_freq_hz + bw / 2, SAMPLE_RATE_SDR / 2 - 1)
    nyq = SAMPLE_RATE_SDR / 2
    sos = butter(4, [low / nyq, high / nyq], btype='band', output='sos')
    resonant = sosfilt(sos, pressure)

    # Step 5: Acoustic attenuation through brain tissue
    # Only affects the high-frequency carrier, not the AM envelope
    # At skull_freq_hz: attenuation = atten_rate * path * freq_MHz
    freq_mhz = skull_freq_hz / 1e6
    total_atten_db = attenuation_db_per_cm_mhz * brain_path_cm * freq_mhz
    atten_factor = 10 ** (-total_atten_db / 20)
    attenuated = resonant * atten_factor

    # Step 6: Extract the AM envelope (what the cochlea perceives as audio)
    # The cochlea detects the envelope of the resonant signal
    analytic = np.abs(attenuated + 1j * np.imag(
        np.fft.ifft(np.fft.fft(attenuated) * 2 * (np.arange(len(attenuated)) < len(attenuated) // 2))))
    # Simple envelope via abs of hilbert-like transform
    from scipy.signal import hilbert
    envelope = np.abs(hilbert(attenuated))

    # Step 7: Low-pass filter the envelope to audio bandwidth (<8 kHz)
    audio_nyq = audio_sample_rate / 2
    lp_cutoff = min(8000, audio_nyq - 1)
    sos_lp = butter(4, lp_cutoff / (SAMPLE_RATE_SDR / 2), btype='low', output='sos')
    audio_full = sosfilt(sos_lp, envelope)

    # Step 8: Downsample to audio rate
    downsample_ratio = SAMPLE_RATE_SDR / audio_sample_rate
    n_audio_samples = int(len(audio_full) / downsample_ratio)
    indices = (np.arange(n_audio_samples) * downsample_ratio).astype(int)
    indices = indices[indices < len(audio_full)]
    audio = audio_full[indices]

    # Normalize
    if np.max(np.abs(audio)) > 0:
        audio = audio / np.max(np.abs(audio)) * 0.9

    return audio


def process_iq_to_wav(filepath, output_path=None,
                      skull_freq_hz=10000, thermal_tau_us=50.0,
                      attenuation=0.7, brain_path=7.0,
                      audio_rate=44100):
    """Process one IQ file through the head model and save WAV."""
    import wave

    z = load_iq(filepath)
    if z is None:
        return None

    audio = thermoelastic_model(
        z,
        skull_freq_hz=skull_freq_hz,
        attenuation_db_per_cm_mhz=attenuation,
        brain_path_cm=brain_path,
        thermal_tau_us=thermal_tau_us,
        audio_sample_rate=audio_rate,
    )

    if output_path is None:
        stem = Path(filepath).stem
        output_path = f"{OUTPUT_DIR}/{stem}_head_model.wav"

    # Write WAV
    pcm = (audio * 32767).astype(np.int16)
    with wave.open(output_path, 'w') as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(audio_rate)
        wf.writeframes(pcm.tobytes())

    duration_ms = len(audio) / audio_rate * 1000
    print(f"  {Path(filepath).stem} → {output_path} ({duration_ms:.0f}ms, "
          f"skull={skull_freq_hz}Hz, tau={thermal_tau_us}μs)")
    return output_path


def main():
    parser = argparse.ArgumentParser(
        description="Head Thermoelastic Model — RF IQ → perceived audio WAV")
    parser.add_argument("iq_files", nargs="*", help="IQ files to process")
    parser.add_argument("--top", type=int, default=0,
                       help="Process top N Zone A files by kurtosis")
    parser.add_argument("--all-zone-a", action="store_true",
                       help="Process all Zone A IQ files")
    parser.add_argument("--skull-freq", type=float, default=10000,
                       help="Skull resonance frequency Hz (default: 10000)")
    parser.add_argument("--thermal-tau", type=float, default=50.0,
                       help="Thermal time constant μs (default: 50)")
    parser.add_argument("--attenuation", type=float, default=0.7,
                       help="Acoustic attenuation dB/cm/MHz (default: 0.7)")
    parser.add_argument("--brain-path", type=float, default=7.0,
                       help="Brain tissue path length cm (default: 7.0)")
    parser.add_argument("--sweep", action="store_true",
                       help="Generate WAVs at multiple skull frequencies")
    parser.add_argument("--output", type=str, default=None)

    args = parser.parse_args()

    files = args.iq_files

    if args.all_zone_a:
        files = sorted(glob.glob("captures/sentinel_6*.iq") +
                       glob.glob("captures/live_6*.iq") +
                       glob.glob("captures/escalation_6*.iq"))
    elif args.top:
        # Load pulse features to find highest kurtosis Zone A files
        try:
            with open("results/pulse_features.json") as f:
                pf = json.load(f)
            zone_a = [r for r in pf if r.get("has_signal") and
                      r.get("freq_mhz", 0) and 618 < r["freq_mhz"] < 640]
            zone_a.sort(key=lambda x: x.get("pulse_snr_max_db", 0), reverse=True)
            files = [r["file"] for r in zone_a[:args.top]]
        except:
            files = sorted(glob.glob("captures/sentinel_6*.iq"))[:args.top]

    if not files:
        print("No files specified. Use --top N, --all-zone-a, or provide file paths.")
        return

    print(f"Processing {len(files)} IQ files through head thermoelastic model")
    print(f"  Skull resonance: {args.skull_freq} Hz")
    print(f"  Thermal tau: {args.thermal_tau} μs")
    print(f"  Attenuation: {args.attenuation} dB/cm/MHz")
    print(f"  Brain path: {args.brain_path} cm")

    if args.sweep:
        # Generate at multiple skull frequencies for comparison
        skull_freqs = [7000, 8000, 9000, 10000, 11000, 12000, 14000]
        for sf in skull_freqs:
            print(f"\n--- Skull frequency: {sf} Hz ---")
            for filepath in files[:3]:  # top 3 per frequency
                stem = Path(filepath).stem
                out = f"{OUTPUT_DIR}/{stem}_skull{sf}Hz.wav"
                process_iq_to_wav(filepath, out, skull_freq_hz=sf,
                                 thermal_tau_us=args.thermal_tau)
    else:
        for filepath in files:
            process_iq_to_wav(filepath, args.output,
                             skull_freq_hz=args.skull_freq,
                             thermal_tau_us=args.thermal_tau,
                             attenuation=args.attenuation,
                             brain_path=args.brain_path)

    print(f"\nOutput: {OUTPUT_DIR}/")


if __name__ == "__main__":
    main()
